apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: rajesh
---
apiVersion: v1
kind: Namespace
metadata:
  name: tharaka